User.create({:username => 'shcallaway', :password => 'Davidson16', :first_name => "sherwood", :last_name => "callaway"})
User.create({:username => 'dglover', :password => 'password', :first_name => "danny", :last_name => "glover"})
Tweet.create({:content => "Hello world!", :user_id => 1})
Tweet.create({:content => "Testing...", :user_id => 1})
Tweet.create({:content => "My name is Sherwood.", :user_id => 1})
